### ISSUE TITLE
JS integrations

### ISSUE THREAD

**Issue by VizuaaLOG** [Wikiki/bulma-extensions#1]
Hey,

I'm currently working on creating a JS integration for the core Bulma components.

I really like how your extensions look, would you be happy for me to create JS integrations for some or all of your components once the core Bulma ones are completed?

I will need help with some of them, such as the Calendar, but I'm to give all of them a go.

[You can find the project here](https://github.com/VizuaaLOG/BulmaJS).

**Comment by Wikiki** [comment]
Hi,

Thanks for your message.

I'd discovered your framework recently and it's a really good idea.
I'll be glad to help you with the integration of my components into it.

Creating basic JS part (especially for calendar) is already in my todo-list.
I propose you to keep in touch when the core Bulma components are ready on your side.

Regards
