### ISSUE TITLE
Nuxt integration

### ISSUE THREAD

**Issue by vince015** [Wikiki/bulma-extensions#101]
Does anyone have luck integrating this with Nuxt? Can't make it work.

**Comment by shredmaster** [comment]
I just include the component directly. works for me.
@import "~bulma-extensions/bulma-timeline/src/sass/index.sass";

**Comment by vince015** [comment]
I followed the instructions in this [page](https://wikiki.github.io/#integration), under From NPM but I am getting this:

`Invalid CSS after "!": expected 1 selector or at-rule, was '!function(e,t){"obj'
      in <project_dir>/node_modules/bulma-carousel/dist/js/bulma-carousel.min.js (line 1, column 1)`

My main scss file looks like this:

`
@import "~bulma";
@import "~buefy/src/scss/buefy";

@import "~bulma-carousel";
`

**Comment by Wikiki** [comment]
Hi,

please use the full path to the sass file in your import rule
```@import "~bulma-extensions/bulma-timeline/src/sass/index.sass"```

the default file provided by ```~bulma-carousel```is the the JavaScript filepath not the Sass one.

regards
