### ISSUE TITLE
Using bulma extensions broke my angular 7 build

### ISSUE THREAD

**Issue by simon-lorenz** [Wikiki/bulma-extensions#103]
Hey there,

I had a problem using bulma extensions in my angular 7 app.

After adding ```"./node_modules/bulma-slider/dist/css/bulma-slider.min.css"``` to the styles array in angular.json, the production build broke with a cryptic webpack error message: 

```
92% chunk asset optimization cleancss-webpack-plugin/path/to/project/node_modules/clean-css/lib/optimizer/level-2/properties/populate-components.js:30
          throw e;
          ^

TypeError: Cannot read property '0' of undefined
```

I found a thread at [https://github.com/jakubpawlowicz/clean-css/issues/1042](https://github.com/jakubpawlowicz/clean-css/issues/1042#issuecomment-413588079) where someone had the same problem and solved it by setting ```extractCss: false``` in angular.json. This solution worked for me too, but it increased the build size a bit. 

I just wanted to let you know because bulma extensions is the only library that I had this issue with and it might prevent other devs from using it.

**Comment by Wikiki** [comment]
Hi @simon-lorenz,

thanks for your feedback.
I'll have a look to understand why my CSS generate this issue.
If you have any idea on how to fix it, please share ;-)

regards

**Comment by Wikiki** [comment]
I'm wondering if its not related to the wrong content in my sass file lines 151, 160, 169 <code>transition: transform .2s ease, -webkit-transform .2s ease</code>

I've updated the source file and the minified one (not on npm yet). Can you try using the last source from github in your project and tell me if its working ?

If it still not working, can you please share a basic Angular Project with me so I'll try to fix it (I'm not familiar with angularjs).

regards

**Comment by simon-lorenz** [comment]
Thanks for investigating, that did the trick!
I updated bulma-slider.min.css manually and it works now.
