### ISSUE TITLE
bulma-timeline import error

### ISSUE THREAD

**Issue by lucafaggianelli** [Wikiki/bulma-extensions#109]
Hi, I import bulma-timeline as suggested in the website but it cannot find the sass file, notice that other extensions work:

```scss
@import 'bulma'; // working
@import '~bulma-pricingtable'; // working
@import '~bulma-timeline'; // not working
```
I noticed that timeline package.json is missing the `main` entry, so i was able to import it with:
```scss
@import '~bulma-timeline/dist/css/bulma-timeline.sass';
```

**Comment by Wikiki** [comment]
Hi,

I'll update package.json file to include correct entry points.
