### ISSUE TITLE
Unrecognized text Switch

### ISSUE THREAD

**Issue by chrisb-bacon** [Wikiki/bulma-extensions#116]
Bulma extensions Version 6.2.5
Bulma 0.7.4
node-sass -v 4.11.0+
Lexical error on line 1: Unrecognized text.
  Erroneous area:
1: $switch-height - ($switch-paddle-offset * 2)

--downgrading works well

Build is breaking and the paddle never displays

**Comment by fatahn** [comment]
I get the same error when building my react app
```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Lexical error on line 1: Unrecognized text.
  Erroneous area:
1: $switch-height - ($switch-paddle-offset * 2)
^..^
```

 "node-sass": "^4.12.0",
"node": "10.15.3",
 "yarn": "1.16.0",
"bulma": "^0.7.4",
"bulma-extensions": "^6.2.5",
