### ISSUE TITLE
A calendar range of a single day!

### ISSUE THREAD

**Issue by jongar** [Wikiki/bulma-extensions#12]
Hi! Thanks for these extensions.

I am having an issue with the calendar, I want to highlight the event. I am using is-active for today and I want to give range-start/end color to another single day. When I assign range-start and range-end, the lighter color leaks.

To clarify, for example here: https://wikiki.github.io/bulma-extensions/calendar... I want only 16 and 20 highlighted like they are without what is between them as they are different events.

How can I do that? Thanks.

**Comment by Wikiki** [comment]
Hi,

I've added the $calendar-range-background-color variable. 
So you can set it to transparent if you don't want to have the lighter background color

**Comment by jongar** [comment]
@Wikiki Thanks, I appreciate it.
