### ISSUE TITLE
Flip tooltips to other positions when near the edge of viewport

### ISSUE THREAD

**Issue by renanmontebelo** [Wikiki/bulma-extensions#124]
This is a feature request, and I realize it's a tricky one that might not be possible without js.

Tooltips, when applied to elements near the edges of the viewport, might get 'rendered' partially outside of it. For instance, this button with a "It's a long sentence text" bottom tooltip:

![image](https://user-images.githubusercontent.com/11399853/63071794-50de1d00-bee6-11e9-9764-d3bc0dba7042.png)

My suggestion is that left/right tooltips could move to top or bottom when this situation occurs; top/bottom ones could do the inverse.

I believe that tippy.js implements this feature as `{flip:true}`

**Comment by Wikiki** [comment]
Hi,

please now use [http://github.com/creativebulma/bulma-tooltip](http://github.com/creativebulma/bulma-tooltip) instead.

regards
