### ISSUE TITLE
Tooltip breaks the date range

### ISSUE THREAD

**Issue by jongar** [Wikiki/bulma-extensions#13]
The tooltip breaks the calendar if there's a range. Please take a look:

![screen shot 2017-11-15 at 2 07 14 pm](https://user-images.githubusercontent.com/4993765/32855005-79126dae-ca0e-11e7-8756-c78fb5cb1fcd.png)

**Comment by Wikiki** [comment]
Set tooltip on the .date-item element.
Due to the use of ::before by both (calendar-date and tooltip) we can't set tooltip on calendar-date element.

**Comment by jongar** [comment]
@Wikiki Doh, you are right. That works. Thanks again.
