### ISSUE TITLE
Tooltip cropped in table-container

### ISSUE THREAD

**Issue by jondoe1337** [Wikiki/bulma-extensions#132]
When using a table-container and showing the tooltip, it is cropped. When the table-container div is removed the tooltip is completely visible.

bulma-tooltip: 3.0.2
bulma: 0.8.0
![tooltip](https://user-images.githubusercontent.com/768498/70527187-9e446100-1b4b-11ea-9c0b-0a3820ba886e.png)

**Comment by Wikiki** [comment]
Hi,

please now use [http://github.com/creativebulma/bulma-tooltip](http://github.com/creativebulma/bulma-tooltip) instead.

regards
