### ISSUE TITLE
Tooltip not displaying

### ISSUE THREAD

**Issue by LyonBlecher** [Wikiki/bulma-extensions#134]
I've downloaded the css and js files from jsdeliver.
I've included the css file in the header and the js file at the end of the body, but tooltips are not displaying. The files are loading properly too.
Essentially no attributes using data are working.

Is there any js code I need to execute to attach them?

**Comment by LyonBlecher** [comment]
So I've solved the problem, I need to also have the tooltip css file for it to work, it isn't included directly in the extensions bulma-extensions.min.css file? or is meant to be?

**Comment by jwosborn** [comment]
I had the same problem and the same solution fixed it. Thanks for posting @LyonBlecher .
