### ISSUE TITLE
Activate tooltip on :hover only (not on :focus) ? 

### ISSUE THREAD

**Issue by dtrckd** [Wikiki/bulma-extensions#138]
Hi,

I have button with a **tooltip** as follows:
```
<button class="button tooltip has-tooltip-fade has-tooltip-left" data-tooltip="Hello"><button>Click me</button>
``` 
When we hover the button, the tooltip shows up, ok.
When we click the button, the tooltip stays on the button.

How can we have the tooltip showing up on :hover only (not on :focus i.e when the button is clicked) ?

**Comment by Wikiki** [comment]
Hi,

please use the new version available here: https://github.com/CreativeBulma/bulma-tooltip
