### ISSUE TITLE
[Info] Included in Bulma Front-end Preset for Laravel

### ISSUE THREAD

**Issue by Laraveldeep** [Wikiki/bulma-extensions#14]
Great extensions!

I have included this extension in Bulma preset package for Laravel. 

https://github.com/laravel-frontend-presets/bulma

Thought at some point bulma users will come looking for adding these functionality on their projects.

Thanks!

**Comment by Wikiki** [comment]
Thank you.

I have added your repository to the README file.

I'll add it to the documentation page soon.
