### ISSUE TITLE
Broken github pages

### ISSUE THREAD

**Issue by kot83** [Wikiki/bulma-extensions#15]
![](http://smh.html-5.me/i/1510883565.png)

**Comment by Laraveldeep** [comment]
Yep
Day before it was there.

**Comment by Wikiki** [comment]
Hi,

Sorry, I've a refactored the documentation but forgot to update all github README files.
I'll do it now.

**Comment by Wikiki** [comment]
It should be fixed.
You can now access to the document directly from the url: https://wikiki.github.io

**Comment by Laraveldeep** [comment]
Thanks!
