### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by eraldinho** [Wikiki/bulma-extensions#16]
Hi,
i'am trying to use your calendar extension in the firestarter app (https://github.com/codediodeio/angular-firestarter). I'm not sure to understand what is the correct way to do this. I have this error:
"TypeError: datepicker_1.DatePicker is not a constructor" when I try to create a new datepicker for a text input in my form.

If I write "@import "~bulma-calendar";" in my styles.scss file I have this error:
Undefined variable: "$radius-small"

I m lost, could you help me please?

Erald

**Comment by Wikiki** [comment]
Hi,

did you install bulma too and import it before importing the extension ?
It seems the extension does not find bulma's variables.

**Comment by Wikiki** [comment]
Hi @eraldinho,

do you still having issue ?

**Comment by eraldinho** [comment]
Hi Wikiki,

I'm sorry, I did not have time to work on my project since my ask for help. But This project is for a professional purpose so I must fulfill it. Be sure I will keep you informed when I will try your solution (certainly in a week or 2). Thanks for your help

**Comment by Wikiki** [comment]
Hi @eraldinho ,

any news ?

**Comment by zdr00** [comment]
If anyone else is looking to include bulma-extensions in firestarter I made it by doing this:

- Install the bulma-extension or just the package you want:

`npm install bulma-extensions`

- Include the .min.css file after the bulma import in scss main file **styles.scss**:

```
@import 'bulma/css/bulma.css';
@import 'bulma-extensions/bulma-pageloader/dist/css/bulma-tagsinput.min.css';
```

- When the package needs javascript include the cdnjs script tag in **index.html**:

`<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bulma-tagsinput@2.0.0/dist/js/bulma-tagsinput.min.js"></script>`

declare it in your component class:

`declare var bulmaTagsinput: any;`

and then call it on ngOnInit() method:

bulmaTagsinput.attach();
