### ISSUE TITLE
Carousel not working

### ISSUE THREAD

**Issue by Rickem** [Wikiki/bulma-extensions#17]
Hi,
I'm trying to get the carousel extension working in my angular app but but no luck. 
I've added the courousel.js script in my index.html. Also, I've installed bulma and bulma-extensions with npm and added @import 'bulma'; in my style.scss which gives me this error: **File to import not found or unreadable: bulma. Parent style sheet: stdin** 

Can you help?

**Comment by Wikiki** [comment]
Hi @Rickem,

this is bulma related. Not extension.
You should post an issue on bulma's repository.

Regards

**Comment by Wikiki** [comment]
Hi @Rickem,

is it working now ?

**Comment by abadilah1** [comment]
it doesn't work on angular 7

**Comment by Wikiki** [comment]
Could you please share a boilerplate Angular 7 project including the extension with me ?So I'll be able to try to find out what's wrong (I'm not an Angular guy but I'll try to find something)

**Comment by abadilah1** [comment]
AppComponent.html:3 ERROR TypeError: Cannot read property 'attach' of undefined

**Comment by abadilah1** [comment]
so after adding both the css and js files in my Angular.json, i imported the bulmaCarousel in my HeaderComponent.ts as ''import { bulmaCarousel } from 'bulma-carousel/dist/js/bulma-carousel.min.js';''
and initilize the .attach method as ''public carousels = bulmaCarousel.attach('.carousel');''
so i got this error back => ''ERROR TypeError: Cannot read property 'attach' of undefined''

**Comment by Wikiki** [comment]
And you have no error with the line <code>import { bulmaCarousel } from 'bulma-carousel/dist/js/bulma-carousel.min.js';</code> ?
It's weird that <code>bulmaCarousel</code> object is null after importing it.

**Comment by abadilah1** [comment]
I used npm to install the package so definitely it is only dist folder I will have which is from the node_modules directory, I don't have the src folder

**Comment by abadilah1** [comment]
Angular has so many possible ways to use, so if you have any better option just  help with the steps pls, i think that's the best thing to do
