### ISSUE TITLE
Not working with vuejs

### ISSUE THREAD

**Issue by anandutk** [Wikiki/bulma-extensions#18]
Hello there! I've been trying to include the extension to my vuejs project. Please tell me the right attribute I should use to do the same.   

This is the error I'm getting-
**_Module not found: Error: Can't resolve 'sass-loader'_**

Thanks in advance!

**Comment by Wikiki** [comment]
Hi,

did you tried:

```npm install sass-loader --save-dev```

and

```npm install --save-dev node-sass```

**Comment by anandutk** [comment]
And how should I include these all files to my project? I'm trying -
**Import bulma from 'bulma-extentions'**

**Comment by Wikiki** [comment]
Please follow documentation at: https://wikiki.github.io/

**Comment by dogversioning** [comment]
Adding this here as it is the only relevant google result atm for bulma extensions and Vue and maybe it will help the next person searching on this. In order to use bulma-extensions with Vue, you need to create a data element to store the results of your attach call in, so that Vue will be aware of the reactiveness inside of the virtual DOM, and then wait for the component to be mounted before actually calling the relevant bulma extension's attach function. An example script section of a component using bulma accordion:

    <script>
        import bulmaAccordion from 'bulma-extensions/bulma-accordion/dist/js/bulma-accordion.min.js'
        import 'bulma-extensions/bulma-accordion/dist/css/bulma-accordion.min.css';
        export default{
            data () {
                return{
                    accordions : []
                }
            },
            mounted: function() {
                    this.accordions = bulmaAccordion.attach()
            },
            name: 'myComponentName',
    }
    </script>

You can import the css globally as well, but the javascript must be imported at the component level.

**Comment by sharmaankit25** [comment]
window.Vue = require('vue');
import Buefy from 'buefy';
import {bulmaAccordion,bulmaSteps} from 'bulma-extensions/dist/js/bulma-extensions.min';
Vue.use(Buefy, {
    defaultIconPack: 'fas',
});

const app = new Vue({
    el: '#app',
    mounted:function(){
        bulmaAccordion.attach();
        bulmaSteps.attach();
    }
});

**Comment by lbssousa** [comment]
This is an example of Vue component I've wrote for a project, which wraps bulma-carousel. You could extend it for any other bulma-extension.

(NOTE: This example depends on another component I've written for bulma-carousel navigation buttons, but it's omitted here).

```
<template>
  <div
    ref="thisCarousel"
    :class="[{
      'carousel': !hero
    }, {
      'hero-carousel': hero
    }, {
      'carousel-animated': animation === 'slide' || animation === 'fade'
    }, {
      'carousel-animate-slide': animation === 'slide'
    }, {
      'carousel-animate-fade': animation === 'fade'
    }]"
    :data-size="size > 1"
    :data-autoplay="autoplay"
    :data-delay="delay"
  >
    <div class="carousel-container">
      <slot/>
    </div>

    <McbCarouselNavigation layout="overlay"/>
  </div>
</template>

<script>
import BulmaCarousel from 'bulma-carousel/dist/js/bulma-carousel.min'

import McbCarouselNavigation from '../molecules/McbCarouselNavigation'

export default {
  name: 'McbCarousel',
  components: {
    McbCarouselNavigation
  },
  props: {
    hero: {
      type: Boolean,
      default: false
    },
    animation: {
      type: String,
      default: 'slide'
    },
    autoplay: {
      type: Boolean,
      default: false
    },
    delay: {
      type: Number,
      default: 5000
    },
    size: {
      type: Number,
      default: 1
    }
  },
  data () {
    return {
      bulmaExtensions: {}
    }
  },
  mounted () {
    this.bulmaExtensions.carousel = new BulmaCarousel(this.$refs.thisCarousel)
  }
}
</script>
```
