### ISSUE TITLE
Steps with changeable content

### ISSUE THREAD

**Issue by itsursujit** [Wikiki/bulma-extensions#20]
Thank you for your great collection of extensions. I'm trying to use Steps extension for Form Wizard.       It would be good if the Steps extension have changeable content like Form Wizard.

**Comment by Wikiki** [comment]
Hi @itsursujit,

actually, It has :-)
But unfortunately its not documented (my bad). Find example below:

```html
<form method="get" action="#" class="steps">
  <div class="step-item is-active is-success">
    <div class="step-marker">1</div>
    <div class="step-details">
      <p class="step-title">Account</p>
    </div>
  </div>
  <div class="step-item">
    <div class="step-marker">2</div>
    <div class="step-details">
      <p class="step-title">Profile</p>
    </div>
  </div>
  <div class="step-item">
    <div class="step-marker">3</div>
    <div class="step-details">
      <p class="step-title">Social</p>
    </div>
  </div>
  <div class="step-item">
    <div class="step-marker">4</div>
    <div class="step-details">
      <p class="step-title">Finish</p>
    </div>
  </div>
  <div class="steps-content">
    <div class="step-content has-text-centered is-active">
      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Username</label>
        </div>
        <div class="field-body">
          <div class="field">
            <div class="control">
              <input class="input" name="username" id="username" type="text" placeholder="Username" autofocus data-validate="require">
            </div>
          </div>
        </div>
      </div>
      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Password</label>
        </div>
        <div class="field-body">
          <div class="field">
            <div class="control has-icon has-icon-right">
              <input class="input" type="password" name="password" id="password" placeholder="Password" data-validate="require">
            </div>
          </div>
        </div>
      </div>
      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Confirm password</label>
        </div>
        <div class="field-body">
          <div class="field">
            <div class="control has-icon has-icon-right">
              <input class="input" type="password" name="password_confirm" id="password_confirm" placeholder="Confirm password" data-validate="require">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="step-content has-text-centered">
      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Firstname</label>
        </div>
        <div class="field-body">
          <div class="field">
            <div class="control">
              <input class="input" name="firstname" id="firstname" type="text" placeholder="Firstname" autofocus data-validate="require">
            </div>
          </div>
        </div>
      </div>
      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Last name</label>
        </div>
        <div class="field-body">
          <div class="field">
            <div class="control has-icon has-icon-right">
              <input class="input" type="text" name="lastname" id="lastname" placeholder="Last name" data-validate="require">
            </div>
          </div>
        </div>
      </div>
      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Email</label>
        </div>
        <div class="field-body">
          <div class="field">
            <div class="control has-icon has-icon-right">
              <input class="input" type="email" name="email" id="email" placeholder="Email" data-validate="require">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="step-content has-text-centered">
      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Facebook account</label>
        </div>
        <div class="field-body">
          <div class="field">
            <div class="control">
              <input class="input" name="facebook" id="facebook" type="text" placeholder="Facebook account url" autofocus data-validate="require">
            </div>
          </div>
        </div>
      </div>
      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Twitter account</label>
        </div>
        <div class="field-body">
          <div class="field">
            <div class="control">
              <input class="input" name="twitter" id="twitter" type="text" placeholder="Twitter account url" autofocus data-validate="require">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="step-content has-text-centered">
      <h1 class="title is-4">Your account is now created !</h1>
    </div>
  </div>
  <div class="steps-actions">
    <div class="steps-action">
      <a href="#" data-nav="previous" class="button is-light">previous</a>
    </div>
    <div class="steps-action">
      <a href="#" data-nav="next" class="button is-primary">Next</a>
    </div>
  </div>
</form>
```

**Comment by itsursujit** [comment]
Thank you for your quick response. How can I validate required fields before moving to next step? Are there any options available?

**Comment by Wikiki** [comment]
You can use the <code>beforeNext</code> option available to provide a method to check on which step you are and do your validation.

**Comment by itsursujit** [comment]
How can I use `beforeNext`?
I'm using `new StepsWizard(document.getElementById("stepsDemo"))`

**Comment by Wikiki** [comment]
just define your method as option like below:

```javascript
 var stepsWizard = new StepsWizard(document.getElementById("stepsDemo"), {
      'beforeNex': function( step_id ) {
        switch( step_id ) {
          case 1:
            // DO YOUR VALIDATION FOR FIRST STEP (steps_id start at 0)
            break;
            ...
          }
      }
    } );
```

**Comment by Wikiki** [comment]
I note on my todo to detail the use of the JS into the documentation ;-)

**Comment by itsursujit** [comment]
Thank you! I think I've just found a bug. When you reach last step i.e. from step 3 to step 4, the next button can be clicked even after it is disabled and taking me back to step 3

**Comment by Wikiki** [comment]
Thanks for the notice. I'll have a look on it.

**Comment by Wikiki** [comment]
Do you have the same issue with the demo on the documentation page ?

**Comment by itsursujit** [comment]
No. The demo wi JS implementation working well there.

**Comment by itsursujit** [comment]
Sure. Give me some minutes

**Comment by itsursujit** [comment]
Here: https://codepen.io/itsursujit/pen/OzEryR

**Comment by Wikiki** [comment]
The issue seems to related to the fact you are using links for navigation button.
If you use button it works.
I'll see how to fix that (not today I need to leave)

**Comment by itsursujit** [comment]
Much Appreciated! Thanks

**Comment by Wikiki** [comment]
I think it's because a link can't be really disabled so my script intercept the click on it.

**Comment by itsursujit** [comment]
In that case placing css `pointer-events: none` might work

**Comment by Wikiki** [comment]
It has been fixed.

**Comment by marctorresbcn** [comment]
Hello, I 'm trying to add a validation to the extension, I have come to this article through google. But it is impossible to instantiate the "StepsWizard" object in order to define "beforeNext". I do not know how I should use it or where I have to define it. I do not want to touch the file "bulma-steps.js"

Thanks for all

**Comment by Wikiki** [comment]
Hi @marctorresbcn ,

<code>just define your method as option like below:

 var stepsWizard = new StepsWizard(document.getElementById("stepsDemo"), {
      'beforeNext': function( step_id ) {
        switch( step_id ) {
          case 1:
            // DO YOUR VALIDATION FOR FIRST STEP (steps_id start at 0)
            break;
            ...
          }
      }
    } );

There is also an onShow onFinish available entry points.</code>

You have to define that into your own JS file after importing the bulma-steps.js file.

**Comment by wang-xi** [comment]
How can i use new StepsWizard().

**Comment by MHassanSaqib** [comment]
"StepsWizard is not defined".  I have imported bulma-steps. 
import bulmaSteps from 'bulma-extensions/bulma-steps/dist/bulma-steps' 
Could you please help me to resolve the issue?

**Comment by ashoktandan007** [comment]
> You can use the `beforeNext` option available to provide a method to check on which step you are and do your validation.

how to prevent from going to next step if validation fails

**Comment by aman54kumar** [comment]
> > You can use the `beforeNext` option available to provide a method to check on which step you are and do your validation.
> 
> how to prevent from going to next step if validation fails

is there any update on this? can this be done?

**Comment by masiref** [comment]
> > > You can use the `beforeNext` option available to provide a method to check on which step you are and do your validation.
> > 
> > 
> > how to prevent from going to next step if validation fails
> 
> is there any update on this? can this be done?

Hi, take a look here: https://github.com/Wikiki/bulma-steps/issues/36#issuecomment-604309323.

Regards.
