### ISSUE TITLE
Fail to build due to undefined variables

### ISSUE THREAD

**Issue by tutuca** [Wikiki/bulma-extensions#23]
Using bulma v0.6.2 and bulma carousel v0.3.5 from npm I get:

    Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js!src/scss/style.scss:
           [0] ./node_modules/css-loader!./node_modules/postcss-loader/lib?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js!./src/scss/style.scss 254 bytes {0} [built] [failed] [1 error]
       
        ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js!./src/scss/style.scss
        Module build failed: 
        $carousel-nav-background: rgba($white, 0.7) !default
                                      ^
              Undefined variable: "$white".
              in /usr/src/app/node_modules/bulma-carousel/carousel.sass (line 1, column 32)

The same happens with bulma-extensions v0.7.4, just complaining on a different file.
.
This is my webpack config if it helps anything http://dpaste.com/0M6DS6S.

**Comment by Wikiki** [comment]
Hi,

You have to install Bulma first. Please read the documentation at wikiki.github.io

**Comment by Wikiki** [comment]
Did you include bulma first ?

**Comment by tutuca** [comment]
I actually did had bulma installed. But I was importing it after the extension. Sorry for the dumb question. Great library!

**Comment by Wikiki** [comment]
No problem.
Glad to know its working now ;-)
