### ISSUE TITLE
not linux user

### ISSUE THREAD

**Issue by BirUdaya** [Wikiki/bulma-extensions#25]
I am not a linux user. Cannot add the Bulma extensions to my project. I am using windows 10. What to do now?

I am a newbe about developing sites.

**Comment by Wikiki** [comment]
Hi @BirUdaya,

you just need to install node.js and npm on windows to be able to install bulma and extensions.
See tuto at http://blog.teamtreehouse.com/install-node-js-npm-windows

regards

**Comment by BirUdaya** [comment]
thank you 👍

**Comment by BirUdaya** [comment]
One thing I have used "<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.0/css/bulma.min.css">" in my code. And my code is working well with Bulma without installing node.js or npm. Only I faced issues with extensions.

**Comment by Wikiki** [comment]
Ok then just import css file of extensions. 

If you still want to use sass then follow documentation at https://wikiki.github.io
