### ISSUE TITLE
Calendar does not work with Firefox

### ISSUE THREAD

**Issue by jcerdan** [Wikiki/bulma-extensions#26]
Hi,

After last calendar update (from 0.1.9 to 0.2.0), calendar does not trigger after selecting text field. Don't know if it's Firefox 58.0.1 problem or bulma-calendar 0.2.0.
This problem appears using overlay as true or false.
It does work fine with Chromium.

Regards

**Comment by Wikiki** [comment]
Hi,

Is there an issue in the console ?

**Comment by jcerdan** [comment]
Hi, 
there's no output on the console. Yes, it also occurs on the documentation page.
Regards

**Comment by Wikiki** [comment]
Hi,

It's working well under Firefox 58 on my side.
<a href="https://ibb.co/eVUAGH"><img src="https://preview.ibb.co/d6caix/calendar_firefox_58.png" alt="calendar_firefox_58" border="0"></a>

**Comment by jcerdan** [comment]
Hi,
apparently it was a bug on Firefox package in Archlinux. Got an update today and now it works fine in Firefox-58.0.1-2
https://www.archlinux.org/packages/extra/x86_64/firefox/

Regads
