### ISSUE TITLE
Carousel sliding switch Features

### ISSUE THREAD

**Issue by wploey** [Wikiki/bulma-extensions#27]
Hey man, you bulma-extensions is awesome. but I find the carousel, not support sliding switch. and I try to expand this carousel.  my code is here https://codepen.io/wploey/pen/PQzLKv not very standard but I still hope you add this features.

**Comment by Wikiki** [comment]
Hi,

thanks.
I'll add this feature soon ;-) thanks for the codepen ;-)

**Comment by Wikiki** [comment]
Fixed by commit 237f84c
