### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by coussej** [Wikiki/bulma-extensions#3]
I manage all my dependencies using npm, including bulma. It would be very useful to publish this repo to npm, so we can add it to package.json and import both bulma and the extensions in a main.sass file.

Thanks!

**Comment by joshmanders** [comment]
I too would like to see all your extensions published to npm. Right now it's a pain to keep up-to-date.

**Comment by Wikiki** [comment]
Hi,

I'll try. I have never created a npm package but I'll see how to do that as soon as possible.

Regards

**Comment by Wikiki** [comment]
Hi,

I've created a NPM package called bulma-extensions in version 0.0.1 (https://www.npmjs.com/package/bulma-extensions)

Let me know if you are facing issues.

Regards

**Comment by joshmanders** [comment]
Is it possible to get each extension published individually? I only use a few, and would like to be able to do `@import "~bulma-pricingtable"` in my sass.

**Comment by Wikiki** [comment]
Hi @joshmanders,

it's already done. I've also added a link to the npm package of each extension on the related documentation page available here: https://wikiki.github.io/bulma-extensions/overview

Regards

**Comment by joshmanders** [comment]
Awesome. Thank you, @Wikiki!

**Comment by coussej** [comment]
Thank you @Wikiki. Both for acting on my request and making such awesome extensions :-)

**Comment by Wikiki** [comment]
You're welcome ;-)
