### ISSUE TITLE
Help requested for Laravel integration

### ISSUE THREAD

**Issue by Wikiki** [Wikiki/bulma-extensions#30]
Hi community,

it seems my extensions have issue with the compilation process used in a Laravel project.
Is there any developer here who could help me to debug it and try to find a configuration working with Laravel ?

regards,

**Comment by backendcoding** [comment]
Are you trying the frontend preset scaffolding with laravel and bulma?

**Comment by Pablo-Take** [comment]
I'm using laravel 5.6 and couldn't import the extensions to my scss
>   File to import not found or unreadable: ~bulma-extensions.
`@import "~bulma";
@import "~bulma-extensions";`
and bulma is loading correctly. Tried many variations of paths but none worked

**Comment by backendcoding** [comment]
Well for an import statement you would just do @import "location_of_bulma_in_your_project/bulma/bulma"; 

There is an easier way to use bulma with laravel and that is the preset frontend commands in the following link:

https://github.com/laravel-frontend-presets/bulma

**Comment by Wikiki** [comment]
Thanks for your answers.
Actually I'm looking for help from a Laravel Developer to help me to document the right way (and debug if required) my extensions into a Laravel project.

**Comment by fcaivano** [comment]
@Wikiki do you still need help with that? Somewhere i can email you?

**Comment by Wikiki** [comment]
Hi @fcaivano

Yes I still need help.
You can email me at wikiki(at)protonmail(dot)com

**Comment by theguywithglasses** [comment]
Anybody with news on this topic? :)

**Comment by Laraveldeep** [comment]
Hi,

I maintain the Bulma + extension package here https://github.com/laravel-frontend-presets/bulma

You might want to use this for fresh Laravel project. So far many users are using it without a problem.

**Comment by Wikiki** [comment]
Thanks a lot.
