### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by poxin13** [Wikiki/bulma-extensions#32]
As a feature request, would be nice to have a position for the badge, or a special class to be used in the nav bar. Currently using it on a nav item will be cut off the page since it's loaded at the top.

**Comment by Wikiki** [comment]
Hi,

actually you can use one of the following modifier:
<code>.is-badge-left</code>
<code>.is-badge-bottom</code>
<code>.is-badge-bottom-left</code>

The documentation about them is currently missing but will be integrated soon.

**Comment by poxin13** [comment]
Oh hey thanks, my fault for not actually checking.

**Comment by Wikiki** [comment]
No problem.
I just update the documentation to reference those modifiers.
