### ISSUE TITLE
Pageloader won't build

### ISSUE THREAD

**Issue by events-jonas-chrisw** [Wikiki/bulma-extensions#33]
I tried pulling in the some extensions seapeartely using npm.
When trying to build the project it fails because of these references at the top of pageloader:

@import "initial-variables.sass"
@import "functions.sass"
@import "derived-variables.sass"
@import "animations.sass"
@import "mixins.sass"
@import "controls.sass"

surely these are loaded by Bulma anyway??

**Comment by Wikiki** [comment]
Hi,

I forgot to update npm package.
It's done now.
