### ISSUE TITLE
How to import all extensions in scss?

### ISSUE THREAD

**Issue by permadiwibisono** [Wikiki/bulma-extensions#34]
I've tried using
`@import 'bulma-extensions/extensions'` following a tutorials.
But i've got error bulma-extensions/extensions not found.
So how to import all extensions in scss correctly?

**Comment by Wikiki** [comment]
Hi,

don't you forget the <code>~</code> or the direct node_modules path ?

**Comment by permadiwibisono** [comment]
`/* index.scss */`
`@import 'node_modules/bulma/bulma';`
`@import 'node_modules/bulma-extensions/extensions';`
I've tried using `~` and `node_modules` but still errors in webpack `File to import not found or unreadable: node_modules/bulma-extensions/extensions.`
I'm using `bulma-extensions: ^1.0.3`. Or different version?

![image](https://user-images.githubusercontent.com/14840070/36714376-8dd18376-1bc4-11e8-9904-d933274660cb.png)

**Comment by Wikiki** [comment]
How did you install extensions ?
Are you including node_modules directory to your loader ?

**Comment by permadiwibisono** [comment]
Install with npm `npm install --save bulma-extensions`. I think my webpack its work. Because when import bulma/bulma in my scss its work. I just following the tutorial but I got error when import bulma-extensions. So how to use your package?

**Comment by weiliang903** [comment]
This is success
`@import '~bulma-extensions/bulma-carousel/dist/bulma-carousel.sass';`

**Comment by permadiwibisono** [comment]
@weiliang903 Its just some extensions what you need to import. How to import all extensions? I think with
`@import '~bulma-extensions/src/extension.sass'`, it will be work. I found `extension.sass` inside `src` of this repo.

**Comment by Wikiki** [comment]
Hi,

thanks @permadiwibisono but you rather should use the file within <code>dist</code> instead <code>src</code>.

I have to update package.json to point to this file (currently it's pointing to extension.sass which doesn't exists)

**Comment by cindykj** [comment]
How would you implement the javascript of Carousel into AngularJS? Thanks!

**Comment by Wikiki** [comment]
Hi,

@mIcHyAmRaNe : thank you for the complement.

@cindykj : There is no implementation into AngularJS and it's not scheduled.  Feel free to fork this repository and create an AngularJS version.

regards

**Comment by rolu315** [comment]
I just added "bulma-extensions/" to each extension import in the src/sass/index/sass file. Then referenced @import "bulma-extensions/src/sass/index.sass"; and it finally started for me. Not for sure if this was the best practice or not, but it worked for me :)

**Comment by AminuSufi585** [comment]
Thanks @rolu315 your method works just fine!

**Comment by Bally26** [comment]
@mIcHyAmRaNe 
Is Carousel navigation working for this?
Or need to handle this manually.
