### ISSUE TITLE
Help importing into Typescript

### ISSUE THREAD

**Issue by danrye** [Wikiki/bulma-extensions#35]
I'm having trouble getting the JS to load via TS within an Angular 5 app. Any advice?

**Comment by Wikiki** [comment]
Hi,

Sorry I never worked with TypeScript :-(

**Comment by danrye** [comment]
Thoughts on a port of this to TS and Angular? I don't have the time now, but I love what you've done here and I'm interested in forking it with that port in mind.

**Comment by Wikiki** [comment]
I don't plan to port extensions on TS and Angular.
Feel free to fork the repo and propose it to the community.
