### ISSUE TITLE
Compiled version

### ISSUE THREAD

**Issue by itwy** [Wikiki/bulma-extensions#4]
First, I'd like to say thanks for your efforts. Amazing work.

Why there isn't precompiled versions?  Compiling from SASS seems like a hassle.

**Comment by Wikiki** [comment]
Hi @itwy,

thank you.

I didn't provide precompiled version because these extensions depend on Bulma's core and to let developers able to customize them using variables.
But I agree it could be good to have precompiled versions of sass files.
I'l try to add them soon.

Regards,

**Comment by itwy** [comment]
Cool. I actually found the instructions on how to compile the extensions after posting this issue and compiled them with ease.

I am going to close the issue for now.
