### ISSUE TITLE
 Reuse beforeNext callback, is possible?

### ISSUE THREAD

**Issue by marctorresbcn** [Wikiki/bulma-extensions#40]
Hello, I am trying to add a validation to the extension, I have come to this article through google. But it is impossible to instantiate the "StepsWizard" object in order to define "beforeNext". I do not know how I should use it or where I have to define it. I do not want to touch the file "bulma-steps.js"

Thanks for all!

**Comment by marctorresbcn** [comment]
I answer to myself:

I have commented on these lines on bulma-steps.js

/*
document.addEventListener('DOMContentLoaded', function() {
  var stepsContainers = document.querySelectorAll('.steps');
  [].forEach.call(stepsContainers, (stepsContainer) => {
    var stepsWizard = new StepsWizard(stepsContainer);
  });
});
*/

And i've redefined it outside

new bulmaSteps(
    document.querySelectorAll('.steps')[0], {
      beforeNext: function(){console.log('hello my friend')}
    }
)

And works fine.

GOD: as posible to have different steps block using different validations on the same project.
BAD: When we update the library we have to be careful to comment the same lines.

**Comment by Wikiki** [comment]
Hi,

you can see the comment https://github.com/Wikiki/bulma-extensions/issues/20#issuecomment-357448004 in issue #20 

regards

**Comment by MHassanSaqib** [comment]
How can I use this function in vue.js component? instead of writing in main js file? Could you please help me to figure out?
