### ISSUE TITLE
Steps - Skipping stages when I include JavaScript implementation

### ISSUE THREAD

**Issue by jeancabral** [Wikiki/bulma-extensions#47]
Hi Im have a problem whn i include this code
`var bulmaSteps =  new bulmaSteps(document.getElementById('stepsDemo'), {
            onShow: (id) => console.log(id)
         })`

The Stage 2 has been ignored. Someone can help me?

My code is here: https://codepen.io/anon/pen/bMPjZB

Thx advance for help!

**Comment by Wikiki** [comment]
Hi,

this is because bulmaSteps is automatically instantiated by the extension itself. so your code instantiate it a second time. Then when you click on next button it's handled twice.

**Comment by Wikiki** [comment]
Please try the last released version.
Remember to call the new <code>.attach(selector, options)</code> method. There is no auto init anymore.
