### ISSUE TITLE
Potential Bug: TagsInput allows duplicate entries

### ISSUE THREAD

**Issue by mallardduck** [Wikiki/bulma-extensions#49]
From the documentation it states that the TagsInput form field is possible due to being based on developit/tags-input. Using the original library I can see that it includes a feature that prevents defaults.

This seems like a cool and useful feature. I'm wondering if there's a bug causing it to not work in this implementation or something else?

**Comment by mallardduck** [comment]
Example of tags-input with duplicate prevention: http://jsfiddle.net/developit/d5w4jpxq/

**Comment by Wikiki** [comment]
Hi, there is the <code>duplicates</code> options to set to <code>false</code> to avoid duplicates.

**Comment by mallardduck** [comment]
@Wikiki ohhh - that's great to hear!

How would one leverage this feature though?

From what I've seen the input element automatically init's itself upon DOM ready. I'm not seeing any method of controlling the setting before this happens, nor a way to modify it after a Tag input is initialized.

I did notice that there's a line of code that checks for this option as an element attribute. However when I tried that it didn't work; i found that this setting was ignored since the check there also looks for `this.options['duplicates']` which always defaults to true.

**Comment by Wikiki** [comment]
arf you're right the condition don't take attribute into account. I'll update it quickly (and also remove the auto init on DOM ready to keep hand on options)

**Comment by Wikiki** [comment]
Can you try with the last fix ?
Please remember to call <code>.attach()</code> static method with options to init TagsInputs.

**Comment by mallardduck** [comment]
Looks like that does resolve the issue!

https://codepen.io/mallardduck/pen/RJPRxZ

**Comment by Wikiki** [comment]
I'm glad to hear :-)

**Comment by mallardduck** [comment]
Hey @Wikiki,

I may have spoke too soon since I was using codepen earlier to test. Now that I have access to my code and have compiled with the new version I can't init the input. I'm having issues accessing `bulmaTagsinput` in general even though I can see the code in my compiled JS file.

So the way I got around that was by modifying my bulma-extensions to use:

```
window.bulmaTagsinput = require('bulma-extensions/bulma-tagsinput/dist/bulma-tagsinput.js');
```

Not sure if that was an intended change or is an issue with my webpack/laravel mix configs.

**Comment by Wikiki** [comment]
Weird. It's not intended. I'll have a look this afternoon.
