### ISSUE TITLE
Request: Comparison Table

### ISSUE THREAD

**Issue by Log1x** [Wikiki/bulma-extensions#5]
Perhaps a Comparison Table would make a nice Bulma extension?

Something similar to [this](https://codepen.io/silencekillsdesign/pen/myggLo?page=1&) maybe? But up to date and mobile responsive.

**Comment by Log1x** [comment]
https://codyhouse.co/demo/products-comparison-table/index.html

**Comment by Wikiki** [comment]
Hi @Log1x,

thanks for the examples. Don't hesitate if you have others.
I'll try to work on this extension before the end of this month.

**Comment by Log1x** [comment]
The only thing I can think of right now is a proper Mega Menu. I know someone else already did an extension for it, but all they did was `position: static` the dropdown container and it's really not a true implementation.

https://codyhouse.co/gem/css-mega-site-navigation/ -- this is pretty over the top, but it's an idea of what would be truly usable. The sidebar for mobile is nice as well -- but their implementation isn't really ideal, especially with them placing the nav outside of the header...

I have a simple mega menu that is working for me-- but it could be done vastly better. Mind you, it's in Stylus using my Bulma.styl fork.

```
// Dropdown Menu
+desktop()
  .navbar
    .has-dropdown
      &:not(:hover)
        .is-megamenu
          display: none

      .is-megamenu
        position: fixed
        top: calc(3.25rem + 32px)
        padding: 2rem 0

        .has-dropdown
          @extend .column
          @extend .column.is-one-quarter
          > .navbar-link
            display: block
            color: $navbar-item-hover-color
            text-transform: uppercase
            font-weight: $weight-bold
            cursor: default
            pointer-events: none
            margin: 0
            padding: 0
            &::after
              display: none

          ul
            display: block
            li
              line-height: 1.75
              padding: 0
              &.active a
                color: $navbar-item-hover-color
              a
                color: $white
                &:hover
                  color: $navbar-item-hover-color

+touch()
  .navbar
    .has-dropdown
      padding: 0 !important
      > .navbar-link
        &::after
          margin-left: 10px
          margin-top: -1px
          color: $primary
          icon: chevron-right
          font-size: 0.7em
      &.is-expanded
        > .navbar-link
          &::after
            icon: chevron-down
      &:not(.is-expanded)
        .navbar-dropdown,
        > ul
          display: none
```

**Comment by Wikiki** [comment]
Hi @Log1x ,

comparison table has been added.
I'll have a look to a mega-menu.

Regards
