### ISSUE TITLE
Accordion. <a> in accordion-header

### ISSUE THREAD

**Issue by sorokinvj** [Wikiki/bulma-extensions#51]
Hi, I got stuck with this (please help if you have time):

I've implemented accordion as part of sidebar menu for catalog, so here the React component code:

```
<div className={("accordion") + (this.state.isActive ? ' is-active' : '')}>
            <div className="accordion-header toggle">
              <a href={parent.url}>
                {parent.name}
              </a>
            </div>

          <div className="accordion-body">
            <ul>
              {categories.filter(category => category.parent_id === parent.id).map((item, index) =>
                <li key={index}>
                  <a href={item.url} className="is-pulled-left">
                    {item.name}
                  </a>
                </li>
              )}
            </ul>
          </div>
        </div>
```

I want user click on header so<a> link fire AND accordion fire up simultanously, so how do I achieve that? Now it's just the accordeon and link doesn't work at all

**Comment by Wikiki** [comment]
Hi,

You have to put your <code>onClick</code> code directly on the <code>a</code> element then use <code>e.preventDefault();</code> in your JavaScript code.

If you are looking for a complete sidebar menu (with responsiveness capability) have a look at https://creativebulma.net//product/genius-menu

Regards

**Comment by sorokinvj** [comment]
Sorry, I think I put it wrong. Again, I need this link
```
 <a href={parent.url}>
     {parent.name}
 </a>
```
to be activated (that is load a page) with the accordion action which is sliding the menu. 

Or by <span> you mean <a>?

In your example by the way when I click on menu headers it's only submenu but no hyperlink is loaded

**Comment by sorokinvj** [comment]
When I move `toggle` from `div` to `a` nothing changes, accordion works perfectly, but `a` is not

**Comment by Wikiki** [comment]
can you please provide a codepen so I'll be able to have a look ?

**Comment by sorokinvj** [comment]
Sure!

The dev server is here – http://dev.braintobrain.ru/raskroechnye-centry-s-chpu

As you see when you click on top-level menu, for example "another hard machinery category" accordion is live, but there is no redirecting to page. Otherwise if you click on sub-item it redirects.

**Comment by Wikiki** [comment]
Hi,

sorry your dev server is not available anymore.
Can you please provide a codepen.io so I'll be able to check your issue

**Comment by Wikiki** [comment]
bulma-accordion package is abandoned in favor of http://github.com/creativebulma/bulma-collapsible.
Please use this new package instead and open an issue on its repository if needed.
