### ISSUE TITLE
【Feature/Request】Different Kind of Card

### ISSUE THREAD

**Issue by ryuukibeat** [Wikiki/bulma-extensions#53]
Hello, 
I'm a newbie in programming, even more CSS.
How to re-design BULMA card component that looks like in the image below?
![Cards](https://puu.sh/Az2e1.png)
With some hover light-shadow and the card-image and button slightly out of the card.

Thank you in advance.

**Comment by Wikiki** [comment]
Hi,

welcome in the delopment world ;-)
First to customize bulma I suggest you to learn Sass (bulma is built on it and propose lots of variables for customization).
