### ISSUE TITLE
Bulma Carousel: Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by smuzammilali** [Wikiki/bulma-extensions#54]
Using Bulma carousel extension under my vuejs project, I have successfully implemented the extension and everything works fine including auto play.

Just having this issue when clicking on either left/right navigation buttons:
![2018-06-05_1134](https://user-images.githubusercontent.com/24757934/40986674-ce77dfd2-68b4-11e8-8603-7fa621872e53.png)

**Comment by Wikiki** [comment]
Hi, it's a known issue. It was just a warning previously.
I'll try to fix that tomorrow.
