### ISSUE TITLE
TagsInput Fails on v.1.1.0

### ISSUE THREAD

**Issue by Laraveldeep** [Wikiki/bulma-extensions#58]
Tagsinput not working on bundle install of v1.1.0. Console doesn't show any warning however previously working tagsinput broke in this version.

**Comment by Laraveldeep** [comment]
@Wikiki referencing the script separately is one way to do it if it is used in single page. The reason we are using webpack it is to compile whatever scripts we have (Vuejs, JQuery, custom scripts used in the app) into single script.

Seems to me extension scripts not working have nothing to do with Laravel or any other framework. It used to work before. Probably something significant have changed in the script.

This is my stand alone test of the Tagsinput in [codepen](https://codepen.io/Laraveldeep/pen/Kevpmg). It is not working either. Bulma 0.7.1 was referenced there together with css copied from `bulma-tagsinput.min.css` and  script copied from `bulma-tagsinput.js`.

Please take a look if I missed something.

This code used to work on previous versions.

Thanks!

**Comment by Wikiki** [comment]
Hi,

your codepen is working.
You just forgot to call <code>.attach()</code> static method to instantiate extension

**Comment by Laraveldeep** [comment]
Ok... Yes it is working.
So we need new `attach()` function.

Let me check what's wrong with Laravel.

**Comment by Laraveldeep** [comment]
@Wikiki 
Ok after some test I am able to solve this issue.

I am getting `undefined` error for all extension that required script. Seems like the factory definition in script is not recognized.

Explicitly defining it solved the problem
```
var bulmaTagsinput = require('bulma-extensions/bulma-tagsinput/dist/bulma-tagsinput');
var tags = bulmaTagsinput.attach();
OR
bulmaTagsinput.attach();
```
Testing other extensions now. 

Will inform in related extension thread if there is a problem.

Any clue from this solution?
