### ISSUE TITLE
is this up to date?

### ISSUE THREAD

**Issue by kresli** [Wikiki/bulma-extensions#6]
https://github.com/aramvisser/bulma-steps contain different sass. I can't reproduce examples from bulma-steps. Is this need to be manually updated?

**Comment by Wikiki** [comment]
Hi @kresli ,

sorry but you are pointing on @kresli aramvisser steps extensions.

Regards

**Comment by kresli** [comment]
Yes you are right. Of course I found it after posting the issue. Thank you.

**Comment by kresli** [comment]
Actually I think I need to reopen this ticket. Installed bulma-extensions doesn't contain latest version of bulma-steps. This [commit](https://github.com/Wikiki/bulma-steps/commit/404c20ba3315b337a28767a8b6b7cd249531b627#diff-d20ceb9652c26e5d67b2f3c34406053b) change `step-content` to `step-details` which doesn't exist in my  bulma-extensions module

**Comment by Wikiki** [comment]
Did you use npm version or github repository ?

**Comment by kresli** [comment]
npm. This could be because you change version from 1.0.0 to 0.5.3. Thats my guess. You always trying to keep it with semantic versioning to make npm happy :) http://semver.org/
>Given a version number MAJOR.MINOR.PATCH, increment the:
>MAJOR version when you make incompatible API changes,
>MINOR version when you add functionality in a backwards-compatible manner, and
>PATCH version when you make backwards-compatible bug fixes.
>Additional labels for pre-release and build metadata are available as extensions to the >MAJOR.MINOR.PATCH format.

Otherwise really good stuff! Thank you.

**Comment by Wikiki** [comment]
My bad I forgot to update bulma-extensions npm with last extensions versions.

It should be working now.
Please let me know.

Regards
