### ISSUE TITLE
Code snippets don't expand to display full code

### ISSUE THREAD

**Issue by karanrajpal14** [Wikiki/bulma-extensions#61]
Hello,

I've noticed this issue throughout the extensions website. None of the code sections seem to be expandable like in Bulma's official documentation.

Look here:
- [Accordion](https://wikiki.github.io/components/accordion/)
- [Calendar](https://wikiki.github.io/components/calendar/)
- [Carousel](https://wikiki.github.io/components/carousel/)

These are just some of the examples but the issue seems to be present throughout the website. Would you please fix it?

**Comment by melTr** [comment]
same in badge also.
Thanks

**Comment by KaotiKcr** [comment]
@Wikiki this is very simple to fix, in the documentation, you are just missing the part 
```
<script>
  bulmaAccordion.attach();
</script>
```

**Comment by karanrajpal14** [comment]
Thank you @KaotiKcr and @Wikiki 😄
