### ISSUE TITLE
Advertise that a vertical divider stretches to the full height?

### ISSUE THREAD

**Issue by StachuDotNet** [Wikiki/bulma-extensions#63]
Small suggestion.

In the documentation for [the divider](https://wikiki.github.io/layout/divider/), I found myself asking "hmm, I wonder if the vertical divider spans the full height of its siblings." 

So, I just went in, edited the HTML locally to test, and was satisfied with the subject.
![image](https://user-images.githubusercontent.com/906686/42137736-e721245e-7d3f-11e8-8302-3637b2effec0.png)
![image](https://user-images.githubusercontent.com/906686/42137734-e4541088-7d3f-11e8-9962-6a85d9f47382.png)

A trivial thing, I know (!), but maybe it's worth showing this off more explicitly.

If you're ok with this, I'm open to submitting a PR. Please let me know if there's any particular content that you have in mind to show this off.

**Comment by Wikiki** [comment]
Hi,

feel free to open a PR to show this ;-)
