### ISSUE TITLE
bulma-tooltip: impossible to hide the tooltip on touch devices

### ISSUE THREAD

**Issue by andreimoment** [Wikiki/bulma-extensions#66]
Open https://wikiki.github.io/elements/tooltip/

Touch the Tooltip sample button. The tooltip appears. 

I would expect that touching the tooltip itself would hide it, or that touching elsewhere on the page (removing focus), would hide it. None of these actions hides the tooltip. 

Any idea on how to approach this?

Showing another tooltip does hide a currently open tooltip.

**Comment by toanmx0101** [comment]
+1

**Comment by Wikiki** [comment]
Hi,

it's related to the major touch issue with this extension. I'll work on it to see how to handle touch devices properly (just missing free time to do it).

**Comment by andreimoment** [comment]
I’ve solved this in the past by adding a js event on (I believe) the body
which would close any open tooltip. At the time I could not find a css only
solution.

That was using another library not bulma.

http://tangomanual.com/tango-lexicon/generator/

**Comment by Wikiki** [comment]
Hi,

please now use [http://github.com/creativebulma/bulma-tooltip](http://github.com/creativebulma/bulma-tooltip) instead.

regards
