### ISSUE TITLE
bulma-carousel

### ISSUE THREAD

**Issue by Pakovia** [Wikiki/bulma-extensions#67]
i have a problem with carousel

> Failed to compile.
> 
> ./node_modules/bulma-carousel/dist/js/bulma-carousel.min.js (./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/lib??ref--6-oneOf-1-2!./node_modules/bulma-carousel/dist/js/bulma-carousel.min.js)
> Module build failed (from ./node_modules/postcss-loader/lib/index.js):
> Syntax Error 
> 
> (1:104) Missed semicolon

thank you

**Comment by Wikiki** [comment]
It seems you are trying compile a javascript file using a css processor. This can't work

**Comment by Pakovia** [comment]
I am using vue-cli3 don't know what do i have to change 😀
