### ISSUE TITLE
Need to update github pages integration section

### ISSUE THREAD

**Issue by toymachiner62** [Wikiki/bulma-extensions#7]
I stumbled for quite a while on integrating the calendar extension into my project.

The 4th bullet on this page https://wikiki.github.io/bulma-extensions/overview#integration says to copy the code from bulma-switch repo. I just did what this said and didn't realize that bulma-switch was a submodule and it took me a while to figure out why the calendar wasn't loading correctly..

**Comment by Wikiki** [comment]
Hi @toymachiner62 ,

as mentionned at the beginning of this paragraph I took "switch" extension as example for the process.

But I agree, maybe I should split process for all and single extension.
