### ISSUE TITLE
npm version not contains style files

### ISSUE THREAD

**Issue by NuruddinBadawi** [Wikiki/bulma-extensions#73]
please check the last version, I installed from NPM but doesn't contains style file

**Comment by NuruddinBadawi** [comment]
some of them like `checkradio`

**Comment by ckz8780** [comment]
Is this due to the typo `"style": "./dist/css/bulma-extensions.moin.css"` on line 101 of `package.json`? Forgive me if not. I'm new to this :)

**Comment by Wikiki** [comment]
Thanks @NuruddinBadawi. It should be related. I'll update it tonight.

**Comment by Grummfy** [comment]
hello,
this is really anoying, when the new release will be made?

thanks

**Comment by Wikiki** [comment]
Hi,

should be good now.
