### ISSUE TITLE
it's possible import bulma-extension directly from CDN?

### ISSUE THREAD

**Issue by powergt** [Wikiki/bulma-extensions#74]
i use bulma importing it from CDN.
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">

i have tryed to add extensions adding a line:
<script src="https://cdn.jsdelivr.net/npm/bulma-extensions@2.2.1/dist/js/bulma-extensions.min.js" integrity="sha256-GKBVbyTU0cwZzeBVLyjQE79ktHL9+Rn1gpDwfX/PoAo=" crossorigin="anonymous"></script>
but don'work.

**Comment by Wikiki** [comment]
Hi,

you can use jsDelivr. Just find the package using its search engine.

for example: https://www.jsdelivr.com/?query=bulma-calendar

**Comment by keyuls** [comment]
For all extensions:
CSS:https://cdn.jsdelivr.net/npm/bulma-extensions@4.0.0/dist/css/bulma-extensions.min.css
JS:https://cdn.jsdelivr.net/npm/bulma-extensions@4.0.0/dist/js/bulma-extensions.min.js

All packages list
https://www.jsdelivr.com/package/npm/bulma-extensions

**Comment by ryeteezy23** [comment]
Hi

im using wordpress, cdn for calendar dont work. i placed it in my header.php and footer.php
any advices?

**Comment by Wikiki** [comment]
Hi,

Don't you forget to include JS file too and call <code>bulmaCalendar.attach()</code> method to instantiate the plugin ?

**Comment by ryeteezy23** [comment]
Yes and still dont work :(

**Comment by Wikiki** [comment]
Can you please share your code ?

**Comment by ryeteezy23** [comment]
In my header.php

    <?php wp_head(); ?>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-extensions@4.0.0/dist/css/bulma- extensions.min.css">

In my footer.php

    <?php wp_footer(); ?>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-extensions@4.0.0/dist/js/bulma-extensions.min.js">

Latest created js file for bulma calendar component global.js

// Initialize all input of type date
var calendars = bulmaCalendar.attach('[type="date"]', options);

// Loop on each calendar initialized
for(var i = 0; i < calendars.length; i++) {
	// Add listener to date:selected event
	calendars[i].on('select', date => {
		console.log(date);
	});
}

// To access to bulmaCalendar instance of an element
var element = document.querySelector('#my-element');
if (element) {
	// bulmaCalendar instance is available as element.bulmaCalendar
	element.bulmaCalendar.on('select', function(datepicker) {
		console.log(datepicker.data.value());
	});
}

In my functions.php

function load_stylesheets(){
   // code where i included the created js file
}


Any thoughts regarding in bulma-calendar to wordpress approach?

**Comment by Wikiki** [comment]
Is there any error in the browser console ?

**Comment by ryeteezy23** [comment]
No error bro. In my console, css and js are already imported but i dont know why the date element cant override the bulma-calendar..

**Comment by Wikiki** [comment]
Correction: you can't use link html tag to include javascript. You must use the following code instead

```
<script src="https://cdn.jsdelivr.net/npm/bulma-calendar@5.0.3/dist/js/bulma-calendar.min.js"></script>
```

**Comment by ryeteezy23** [comment]
I try dude, I paste the bulma-calendar.min.js ito my assets and register it to functions.php

**Comment by Wikiki** [comment]
As you can see here: https://codepen.io/CreativeBulma/pen/wZapyb it's working using JsDelivr files.

You gave me the code
In my header.php
```
<?php wp_head(); ?>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-calendar@5.0.3/dist/css/bulma-calendar.min.css">
```
In my footer.php
```
<?php wp_footer(); ?>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-calendar@5.0.3/dist/js/bulma-calendar.min.js">
```

But the code in your footer can't work. To include a JavaScript in your file you must use <code><script src="https://cdn.jsdelivr.net/npm/bulma-calendar@5.0.3/dist/js/bulma-calendar.min.js"></script></code>.

**Comment by ryeteezy23** [comment]
Oh i see nice! What a dumb error of mine. Ill try it again tomorrow!

**Comment by Wikiki** [comment]
no problem. We all do this kind of dummy errors ;-)

**Comment by ryeteezy23** [comment]
I liked Bulma because of its simplicity. Two thumbs up for you man! You saved us!

**Comment by Wikiki** [comment]
I oove it for the same reason and that's why I'm creating these extensions and having creating https://creativebulma.net to try developing the ecosystem around bulma.

**Comment by ryeteezy23** [comment]
Hi why bulmaCalendar.attach is not defined after i properly set the link and script via JsDelivr files?

**Comment by Wikiki** [comment]
Did you try v6.0.4 or 5.0.3 ? Tey the last version (6.0.4) as in the codepen

**Comment by ryeteezy23** [comment]
v5.0.3, how did you integrated the bulmaCalendar.attach() ?

**Comment by Wikiki** [comment]
In the url just replace 5.0.3 by 6.0.4

**Comment by ryeteezy23** [comment]
How about this part, im having error in my console that bulmaCalendar.attach not defined

`// Initialize all input of type date
var calendars = bulmaCalendar.attach('[type="date"]', options);

// Loop on each calendar initialized
for(var i = 0; i < calendars.length; i++) {
// Add listener to date:selected event
calendars[i].on('select', date => {
console.log(date);
});
}

// To access to bulmaCalendar instance of an element
var element = document.querySelector('#my-element');
if (element) {
// bulmaCalendar instance is available as element.bulmaCalendar
element.bulmaCalendar.on('select', function(datepicker) {
console.log(datepicker.data.value());
});
}`

**Comment by Wikiki** [comment]
Have you fixed the way you include the javascript part and use the last version (6.0.4)?
Also, are you calling bulmaCalendar.attach() after the inclusion of the jsdelivr file ?

**Comment by ryeteezy23** [comment]
Yes, i put the latest cdn for calendar.

**Comment by Wikiki** [comment]
And ", are you calling bulmaCalendar.attach() after the inclusion of the jsdelivr file ?"

**Comment by Wikiki** [comment]
It llooks like your code is called but the calendar js file is not loaded

**Comment by ryeteezy23** [comment]
Yes in my global.js

I got my first error in var calendars = bulmaCalendar.attach('[type="date"]', options);
where bulmaCalendar.attach() is not defined.

**Comment by Wikiki** [comment]
Please share your projet code on a git repository so I'll be able to help you.
