### ISSUE TITLE
timePicker

### ISSUE THREAD

**Issue by Observablerxjs** [Wikiki/bulma-extensions#75]
Would it be possible to have a timepicker as the one in PrimeNG (Time Only) ([https://www.primefaces.org/primeng/#/calendar](url))

**Comment by SodomousPrime** [comment]
It would be really good if there where a time picker that is as clean as the date picker.

**Comment by flowdee** [comment]
+1

**Comment by Wikiki** [comment]
Hi,

please have a look at my calendar extension v6.0.0 which inclues timepicker.

Regards
