### ISSUE TITLE
is it possible to change the carousel's size?

### ISSUE THREAD

**Issue by maurciobuffa** [Wikiki/bulma-extensions#77]
Hi, it is possible reduce the size of a carousel 's component? I want to reduce it in desktop. In mobile it's look great, but in desktop it looks so big.
Thanks.

**Comment by Wikiki** [comment]
Hi,

Try to put it into a column with sizes modifiers.

**Comment by maurciobuffa** [comment]
Solved! 
Many thanks @Wikiki
