### ISSUE TITLE
Bulma-Carousel Does't work for single Item

### ISSUE THREAD

**Issue by Lahori-Jawan** [Wikiki/bulma-extensions#82]
I am experimenting Bulma carousel (css only) for personal use & found that It does't work for single item. I thought my `.js` logic had flaw but to verify I went to online [docs](https://wikiki.github.io/components/carousel/#navigation) and just deleted all except the one with `order: 1` item and noticed same issue as mine. Is it Intentionl or Bug?

**Comment by Wikiki** [comment]
Hi,

You're right. Currently it works with a least 3 items.

**Comment by Lahori-Jawan** [comment]
mine works with atleast 2 :)

**Comment by Wikiki** [comment]
It's a bug. I didn't figure out how to fix it yet.

**Comment by Lahori-Jawan** [comment]
@Wikiki can you explain me how the sliding transition works? I can't get my head around it. Thanks

**Comment by Wikiki** [comment]
It's inspired by https://blog.envylabs.com/the-order-property-flexbox-carousels-87a168567820
