### ISSUE TITLE
Divider background bug

### ISSUE THREAD

**Issue by saravanabalagi** [Wikiki/bulma-extensions#83]
In Divider css, `is-divider` contains explicit `#fff` which does not allow this component to be used anywhere where the background is not white unless explicitly overridden.

An example where divider is used in a grey background:

![image](https://user-images.githubusercontent.com/8567893/45625985-22618300-ba86-11e8-81d7-816809a418ea.png)

**Comment by philippeluickx** [comment]
Looking at the code, there has been a new parameter introduced:
$divider-content-background-color

It's not documented though.

**Comment by Wikiki** [comment]
Hi,

please use the new version available here: https://github.com/CreativeBulma/bulma-divider
