### ISSUE TITLE
Import enhancements? 

### ISSUE THREAD

**Issue by ckz8780** [Wikiki/bulma-extensions#85]
Hello! I might be importing this incorrectly and if so please feel free to close this issue but I wanted to share my process and a potential enhancement.

As a disclaimer, I'm using webpack and have customized some standard bulma variables, so here's some selected relevant info from my implementation:

**my project's package.json**
```
"scripts": {
  "test": "echo \"Error: no test specified\" && exit 1",
  "sass-dev": "webpack --mode development ./lfa_lite/webpack_src/bulma-index.js --output ./lfa_lite/static/vendor/bulma/js/bulma-bundle.js",
  "react-dev": "webpack --mode development ./lfa_lite/webpack_src/index.js --output ./lfa_lite/apps/dashboard/static/dashboard_react_static/main.js",
  "dev": "npm run sass-dev && npm run react-dev",
  "build": "webpack --mode production ./lfa_lite/apps/dashboard/src/index.js --output ./lfa_lite/apps/dashboard/static/dashboard_react_static/main.js"
},
```

**bulma-index.js**

`require("./mystyles.scss");`

**mystyles.scss**

```
/* other styles/variable customizations per bulma docs and then... */

@import "~bulma/bulma";
@import "~bulma-extensions";
```

So, this fails `npm run dev` (see above for what that script does with a `Not enough space` error. Ok no problem... so I change **mystyles.scss** to:

```
/* other styles/variable customizations per bulma docs and then... */

@import "~bulma/bulma";
@import "~bulma-extensions/bulma-extensions";
```

...thinking (not knowing anything about bulma extensions cause I'm new) that it works similar to bulma itself, which also fails, this time with `File to import not found or unreadable: ~bulma-extensions/bulma-extensions`. Again, no biggie, so I dig into the node package to see where the main imports are located and find `/node_modules/bulma-extensions/dist/css/bulma-extensions.sass` which looks like the main file similar to bulma's `bulma.sass` -- alrighty! So I update **mystyles.scss** again to:

```
/* other styles/variable customizations per bulma docs and then... */

@import "~bulma/bulma";
@import "~bulma-extensions/dist/css/bulma-extensions";
```

...which now fails `npm run dev` with `File to import not found or unreadable: bulma-accordion/src/sass/index.sass.` So out of curiosity, I change **bulma-extensions.sass** to:

```
@charset "utf-8"

@import "../../bulma-accordion/src/sass/index.sass"
@import "../../bulma-badge/src/sass/index.sass"
@import "../../bulma-calendar/src/sass/index.sass"
@import "../../bulma-carousel/src/sass/index.sass"
@import "../../bulma-checkradio/src/sass/index.sass"
@import "../../bulma-divider/src/sass/index.sass"
@import "../../bulma-iconpicker/src/sass/index.sass"
@import "../../bulma-pageloader/src/sass/index.sass"
@import "../../bulma-pricingtable/src/sass/index.sass"
@import "../../bulma-quickview/src/sass/index.sass"
@import "../../bulma-ribbon/src/sass/index.sass"
@import "../../bulma-slider/src/sass/index.sass"
@import "../../bulma-steps/src/sass/index.sass"
@import "../../bulma-switch/src/sass/index.sass"
@import "../../bulma-tagsinput/src/sass/index.sass"
@import "../../bulma-timeline/src/sass/index.sass"
@import "../../bulma-tooltip/src/sass/index.sass"
```

**And it works! So here's my proposition:**

Can we either add an **all.sass** in the root bulma-extensions folder which mirrors bulma-extensions.sass, so that we can `@import ~bulma-extensions/all` in our **mystyles.scss**, or update the `bulma-extensions/dist/css/bulma-extensions.sass` file to include the relative paths as I've done so that we can `@import "~bulma-extensions/dist/css/bulma-extensions"`? 

If all of this is just silly and I'm just not importing it correctly, could you please share how to import both the CSS and the JS if we've customized bulma and are using webpack? 

On an unrelated note, there's a typo on line 101 of package.json: `"style": "./dist/css/bulma-extensions.moin.css",` should be `"style": "./dist/css/bulma-extensions.min.css",` (I think) 

Thank you for any input! Awesome library btw!

**Comment by barayuda** [comment]
Thank you, I just following this step. And worked smoothly.

+1 for your suggestion, I hope any proposal for this in next update. cc @Wikiki 

Thank you. Awesome library!

**Comment by Wikiki** [comment]
main sass file has been updated with relative path and package.json now includes <code>style</code> and <code>sass</code> fields to import the right file based on context.
