### ISSUE TITLE
angular-client 6 problem when @import '~bulma-extensions'

### ISSUE THREAD

**Issue by cirix** [Wikiki/bulma-extensions#86]
Hi guys,
I have the following error when adding to my style.sass the following command:

`import '~bulma-extensions'`

> ERROR in ./src/styles.sass (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/styles.sass)
Module build failed: Not enough space
...42.3 kB  [rendered]
chunk {main} main.js, main.js.map (main) 51.8 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 8.31 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 15.9 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.87 MB [initial] [rendered]
ℹ ｢wdm｣: Failed to compile.

> Machine Macbook Pro working on latest stable angular version and angular-cli 6. Same for npm versions. Bare in mind I have 16GB of RAM in a 8 core machine.

Please can you advise?
@Wikiki any support with this error would be nice or a clear statement if extensions are working with
angular-cli 6 or similar.

**Comment by Wikiki** [comment]
Hi,

the default impoe uses the sass file.
Specify the js dist folder to fix this error:
```js
@import '~bulma-extensions/dist/js/bulma-extensions.js
```

**Comment by Wikiki** [comment]
The right path is the following (not the js one - sorry):

```@import '~bulma-extensions/dist/css/bulma-extensions.sass```
