### ISSUE TITLE
Adding 'off' option for switches.

### ISSUE THREAD

**Issue by EnderDev** [Wikiki/bulma-extensions#97]
Hi, when I was playing around with switches and using them in forms, I realized that if the switch isn't checked it won't send any data. So if both switches are off, no post params are sent. If they are checked they return 'ok'. Could you add a option, so it shows 'off' if it's not checked.

If not, is there a way around this?

Thanks, EnderDev

**Comment by Wikiki** [comment]
Hi,

this is the default behavior for checkboxes.
Maybe you can try solution like: https://stackoverflow.com/questions/1809494/post-unchecked-html-checkboxes
