### ISSUE TITLE
Can't seem to make tagsinput to work

### ISSUE THREAD

**Issue by Thatkookooguy** [Wikiki/bulma-extensions#99]
Here's a minimal pen of what I'm trying:
https://codepen.io/neilkalman/pen/roKqrJ?editors=1000

basically, I'm including the css and javascript files required along side a bulma theme, but it looks like the input is never activated (it remains a normal input text field). I copied the input snippet from the documentation.

Can someone please point to what's missing from my pen to make this work?

thanks in advance!

**Comment by thomis** [comment]
I had the same problem. 
Looking at the source of the demo page towards the end you can see they also did

 `<script>bulmaTagsinput.attach();</script>`

In addition I had to load the the javascript file like so

`import bulmaTagsinput from "bulma-extensions/bulma-tagsinput/dist/js/bulma-tagsinput.min.js"`

Hope that helps.

**Comment by Thatkookooguy** [comment]
@thomis yes! that solved it! should have looked at the demo source code 😅 

Thanks for helping out!
